// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDstAeeMo5vEwATUeaC8QRhrmjuVpaYY5U',
    appId: '1:383013120334:web:569d5971bb489d2c1c561f',
    messagingSenderId: '383013120334',
    projectId: 'bearbuddy-c22f7',
    authDomain: 'bearbuddy-c22f7.firebaseapp.com',
    storageBucket: 'bearbuddy-c22f7.firebasestorage.app',
    measurementId: 'G-NVSB3FV1XH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHjuPcNFzf9Hgdjsoue3_sgbwwKoF_ufQ',
    appId: '1:383013120334:android:97c06b26583812341c561f',
    messagingSenderId: '383013120334',
    projectId: 'bearbuddy-c22f7',
    storageBucket: 'bearbuddy-c22f7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCEUJcTAP5c6EpOwcQl4O5mxZtGLFQIYrY',
    appId: '1:383013120334:ios:9f61df5a294a9a871c561f',
    messagingSenderId: '383013120334',
    projectId: 'bearbuddy-c22f7',
    storageBucket: 'bearbuddy-c22f7.firebasestorage.app',
    iosBundleId: 'com.example.studentApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCEUJcTAP5c6EpOwcQl4O5mxZtGLFQIYrY',
    appId: '1:383013120334:ios:9f61df5a294a9a871c561f',
    messagingSenderId: '383013120334',
    projectId: 'bearbuddy-c22f7',
    storageBucket: 'bearbuddy-c22f7.firebasestorage.app',
    iosBundleId: 'com.example.studentApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDstAeeMo5vEwATUeaC8QRhrmjuVpaYY5U',
    appId: '1:383013120334:web:28c2c5119f98340e1c561f',
    messagingSenderId: '383013120334',
    projectId: 'bearbuddy-c22f7',
    authDomain: 'bearbuddy-c22f7.firebaseapp.com',
    storageBucket: 'bearbuddy-c22f7.firebasestorage.app',
    measurementId: 'G-HR07QN4JTZ',
  );
}
