# analysis_options.yaml

include: package:flutter_lints/flutter.yaml

linter:
  rules:
    # Common useful rules
    avoid_print: true # Prefer using a logger instead
    prefer_const_constructors: true # Use const constructors when possible
    prefer_final_locals: true # Use final for local variables where possible
    unnecessary_this: true # Avoid using `this.` when not needed
    prefer_single_quotes: true # Enforce single quotes for strings
    sort_child_properties_last: true # Sort child last in widgets for readability

    # Readability & maintainability
    always_put_control_body_on_new_line: true
    prefer_expression_function_bodies: true
    use_key_in_widget_constructors: true
    sized_box_for_whitespace: true

    # Optional: Enforce documentation
    public_member_api_docs: false # Enable if you want to require doc comments

analyzer:
  exclude:
    - "**/*.g.dart" # Ignore generated files
    - "**/*.freezed.dart"
    - "**/generated/**"
